version: "3.9"

services:
  db:
    image: postgres:16
    container_name: roleferry_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roleferry
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
  backend:
    build:
      context: ./backend
    container_name: roleferry_backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - ENV=dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db
      - redis
    image: redis:7
    container_name: roleferry_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  db_data:
    driver: local

